import { Manufacturers } from './manufacturers';
export interface Product {
  id:number,
  title:string,
  reference?:string,
  isNew?:boolean,
  isTrend?:boolean,
  colors?:string[],
  sizes?:string[],
  discount:number,
  stock:number,
  imagePath:string,
  images?:string[],
  desc?:string,
  subCategoryId?:number,
  categoryId?:number,
  mainCategoryId?:number,
  src?:string,
  ManufacturerId?:number,
  // srcHover?:string,
  // srcSmall?:string,
  noOfReviews:number,
  rate:number,
  old:string,
}
